### PR TITLE
Group sub-tests

### LINKED ISSUE #4: Group sub-tests instead of creating multiple tickets
Within Go, one common pattern is to use table tests for testing specific scenarios.

In case there are failures that are related to more than one of these tests, you will receive a JUnit report as such:
```xml
<testcase name="TestDifferentBaseTypes" classname="github.com/stackrox/rox/pkg/booleanpolicy/evaluator" time="0.050">
    <failure message="Failed"/>
</testcase>
<testcase name="TestDifferentBaseTypes/base_ts,_query_by_relative,_does_not_match" classname="github.com/stackrox/rox/pkg/booleanpolicy/evaluator" time="0.000">
    <failure message="Failed"/>
</testcase>
<testcase name="TestDifferentBaseTypes/base_ts,_query_by_relative,_does_not_match/on_fully_hydrated_object" classname="github.com/stackrox/rox/pkg/booleanpolicy/evaluator" time="0.000">
    <failure message="Failed">
        <![CDATA[ evaluator_test.go:96: Error Trace: /go/src/github.com/stackrox/stackrox/pkg/booleanpolicy/evaluator/evaluator_test.go:96 /go/src/github.com/stackrox/stackrox/pkg/booleanpolicy/evaluator/evaluator_test.go:123 Error: Not equal: expected: false actual : true Test: TestDifferentBaseTypes/base_ts,_query_by_relative,_does_not_match/on_fully_hydrated_object ]]>
    </failure>
</testcase>
<testcase name="TestDifferentBaseTypes/base_ts,_query_by_relative,_does_not_match/on_augmented_object" classname="github.com/stackrox/rox/pkg/booleanpolicy/evaluator" time="0.000">
    <failure message="Failed">
        <![CDATA[ evaluator_test.go:96: Error Trace: /go/src/github.com/stackrox/stackrox/pkg/booleanpolicy/evaluator/evaluator_test.go:96 /go/src/github.com/stackrox/stackrox/pkg/booleanpolicy/evaluator/evaluator_test.go:145 Error: Not equal: expected: false actual : true Test: TestDifferentBaseTypes/base_ts,_query_by_relative,_does_not_match/on_augmented_object ]]>
    </failure>
</testcase>
```

This currently leads to four different issues being created, as JUnit reports 4 failures (example issues: ROX-14129,ROX-14130,ROX-14131,ROX-14132).

It would be nicer to try and group certain failures if they are stemming from table tests.

I haven't found anything in the spec that would allow us to re-use something, so I would propose the delimiters provided (`/`) as indicators of sub-tests.

The logic I would follow would be:
- In case there are multiple failures,
- From the _same classname_,
- containing a `/` within their name,
group them and create a single issue / comment from them.

### PR DESCRIPTION
**Pull request by dhaus67**
The PR will allow grouping for sub-tests to avoid creating multiple tickets + adds the `Errors` field to the ticket description which holds more information than the typical `Failed` message we receive.

Closes #4

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -197,6 +197,32 @@ func findFailedTests(dirName string, env map[string]string, threshold int) ([]te
...
 
+func addFailedTest(failedTests []testCase, tc junit.Test, env map[string]string) []testCase {
+	if !isSubTest(tc) {
+		return append(failedTests, NewTestCase(tc, env))
+	}
+	return addSubTestToFailedTest(tc, failedTests, env)
+}
+
+func isSubTest(tc junit.Test) bool {
+	return strings.Contains(tc.Name, "/")
```
Comment (janisz) [inline main.go:208]: Although this condition is true for go subtests it's not enough as it will merge tests from e2e that contains `/` in their names (see https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_stackrox/4254/pull-ci-stackrox-stackrox-master-gke-postgres-qa-e2e-tests/1609808665097801728) 
How about checking if test name is prefixed with previous test name or at least if test is go by checking classname to contains golang package.

Comment (dhaus67) [reply main.go:231]: Added the check to ensure we only attempt to group go tests based on the go module's prefix.

**Review by janisz — APPROVED** [review]
